package com.ledgerops.ledger.api;

public enum ReversalLedgerError {
    ORIGINAL_PAYMENT_POSTING_MISSING,
    ORIGINAL_PAYMENT_POSTING_MISMATCH,
    REVERSAL_SOURCE_ALREADY_POSTED,
    REQUIRED_ACCOUNT_NOT_FOUND,
    REQUIRED_ACCOUNT_INVALID
}
