package com.ledgerops.ledger.api;

public enum SettlementCorrectionLedgerError {
    ORIGINAL_TRANSACTION_NOT_FOUND,
    ORIGINAL_TRANSACTION_NOT_SETTLEMENT_ADJUSTMENT,
    TARGET_ALREADY_COMPENSATED,
    SOURCE_ALREADY_POSTED,
    SOURCE_POSTING_MISMATCH,
    POSTING_FAILED
}
