package com.ledgerops.risk.api;

public enum RiskConfigurationError {
    INVALID_AMOUNT_THRESHOLD,
    INVALID_SCORE_CONTRIBUTION,
    INVALID_THRESHOLD_ORDER,
    PROFILE_RULE_MISMATCH,
    NO_ACTIVE_PROFILE,
    MULTIPLE_ACTIVE_PROFILES,
    INACTIVE_PROFILE,
    TENANT_PROFILE_MISMATCH,
    NO_ELIGIBLE_RULE
}
