package com.ledgerops.reconciliation.domain;

public enum ReconciliationDiscrepancyCategory {
    MISSING_INTERNAL_PAYMENT,
    MISSING_PROVIDER_RECORD,
    MISSING_INTERNAL_REVERSAL,
    MISSING_PROVIDER_REVERSAL,
    AMOUNT_MISMATCH,
    CURRENCY_MISMATCH,
    STATUS_MISMATCH,
    DUPLICATE_PROVIDER_RECORD,
    DUPLICATE_INTERNAL_REFERENCE,
    LEDGER_TRANSACTION_MISSING,
    LEDGER_AMOUNT_MISMATCH,
    SETTLEMENT_DATE_MISMATCH,
    UNRESOLVED_PROVIDER_REFERENCE,
    INVALID_PROVIDER_RECORD,
    REVERSAL_WITHOUT_PAYMENT_SETTLEMENT
}
