package com.ledgerops.reconciliation.domain;

public enum SettlementValidationReasonCode {
    INVALID_HEADER,
    INVALID_UTF8,
    FILE_TOO_LARGE,
    TOO_MANY_ROWS,
    INCONSISTENT_BATCH_IDENTITY,
    INVALID_FIELD,
    UNSUPPORTED_CURRENCY,
    DUPLICATE_PROVIDER_RECORD,
    CONFLICTING_PROVIDER_RECORD,
    SUBJECT_NOT_FOUND,
    PROVIDER_REFERENCE_MISMATCH,
    AMOUNT_MISMATCH,
    CURRENCY_MISMATCH,
    STATUS_MISMATCH,
    SETTLEMENT_DATE_MISMATCH
}
