CREATE TABLE reporting.payment_timeline_stream_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projection_name VARCHAR(80) NOT NULL,
    source_message_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    payment_id UUID NOT NULL,
    merchant_id UUID,
    source_module VARCHAR(80) NOT NULL,
    source_type VARCHAR(120) NOT NULL,
    source_id UUID NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    actor_source VARCHAR(120) NOT NULL,
    outcome VARCHAR(120) NOT NULL,
    reason_code VARCHAR(160),
    correlation_id UUID,
    display_text TEXT NOT NULL,

    CONSTRAINT uk_payment_timeline_stream_source
        UNIQUE (projection_name, source_message_id),
    CONSTRAINT ck_payment_timeline_stream_projection_name
        CHECK (length(trim(projection_name)) > 0),
    CONSTRAINT ck_payment_timeline_stream_source_module
        CHECK (length(trim(source_module)) > 0),
    CONSTRAINT ck_payment_timeline_stream_source_type
        CHECK (length(trim(source_type)) > 0),
    CONSTRAINT ck_payment_timeline_stream_actor_source
        CHECK (length(trim(actor_source)) > 0),
    CONSTRAINT ck_payment_timeline_stream_outcome
        CHECK (length(trim(outcome)) > 0),
    CONSTRAINT ck_payment_timeline_stream_display_text
        CHECK (length(trim(display_text)) > 0)
);

CREATE INDEX ix_payment_timeline_stream_tenant_cursor
    ON reporting.payment_timeline_stream_event (tenant_id, event_id);
